#!/bin/bash
#
# Checks if a host can be pinged and sends an email alert if ping fails. 
#
# Original author: Tim West <tim@greenmtnit.com>
#
# Copyright (C) 2022 Green Mountain IT Solutions, LLC <info@greenmtnit.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

PROGNAME=$(basename "$0")
readonly PROGNAME

PROGDIR=$(readlink -m "$(dirname "$0")")
readonly PROGDIR

# Print a status message
print_status() {
  echo
  echo "$1"
  echo
}

# Print an error message to stderr in red
print_err() {
  tput setaf 1
  printf -- '[ERROR] %s\n' "${*}" >&2
  tput sgr0
}

# Print an error message in red and exit the script
die() {
  print_err "${*}"
  exit 1
}

send_email() {
  local subject
  local message
  message="$1"
  subject="Ping failed alert on $(hostname -f)"
  echo "$message" | mail -s "$subject" "$dest_addr" 
}

show_help() {
    cat <<EOF
    Usage: $PROGNAME options

    This script checks if a host can be pinged and send an email alert if the ping fails. 

    Options:
       -t --target            Target hostname or IP for ping
       -d --dest              Destination to send emails to. 
       -h --help              Show this help.

    
    Examples:
       Ping 192.168.1.1 and send an email to me@mydomain.com if ping fails. 
       $PROGNAME -t 192.168.1.1 -d me@mydomain.com
EOF
}

# Initialize all the option variables.
# This ensures we are not contaminated by variables from the environment.
dest_addr=
target=

if [ -z "$1" ]; then
  print_err "No arguments given. This program requires arguments."
  show_help
  exit 
fi

while :; do
    case $1 in
        -h|-\?|--help)
            show_help    # Display a usage synopsis.
            exit
            ;;
        -t|--target)       # From email address.
            if [ "$2" ]; then
                target="$2"
                shift
            else
                die 'ERROR: "--target" requires a non-empty option argument.'
            fi
            ;;
        -d|--dest)       # Destination email address.
            if [ "$2" ]; then
                dest_addr="$2"
                shift
            else
                die 'ERROR: "--dest" requires a non-empty option argument.'
            fi
            ;;
        --)              # End of all options.
            shift
            break
            ;;
        -?*)
            printf 'WARNING: Unknown option (ignored): %s\n' "$1" >&2
            ;;
        *)               # Default case: No more options, so break out of the loop.
            break
    esac
    shift
done

check_options() {
  if [ -z "$target" ]; then
    print_err "You must set a target hostname or IP to ping using --target."
    show_help
    exit 1
  fi

  if [ -z "$dest_addr" ]; then
    print_err "You must set a destination email address using --dest."
    show_help
    exit 1
  fi
}  


check_ping() {
  if ping -c 3 $target &> /dev/null; then
    echo "Pinging $target successful"
  else 
    echo "WARNING! Pinging $target failed!"
   send_email "WARNING! Pinging $target failed on host $(hostname -f). You should investigate!!"
  fi
}

main() {
  check_options
  check_ping
}

main
